Transform: AWS::Serverless-2016-10-31
Description: __DESCRIPTION__

Parameters:
  EnvStage:
    Type: String
    Default: dev

Resources:
  # Lambda Function
  LambdaApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rust.handler
      Runtime: provided.al2023
      CodeUri: target/lambda/__PROJECT_NAME__/
      Environment:
        Variables:
          TABLE_NAME: __PROJECT_NAME__
          AWS_SAM_LOCAL: http://host.docker.internal:8000
          PUB_KEY: H8nfwRco3FxcD2r8MvtPuW7N7mFJLNDQFNZUhUCqWDM=
          PRV_KEY: p3mT73gXTe8CKykJOETDj0gIa2vlgFqH9jk5HOLR9MYfyd/BFyjcXFwPavwy+0+5bs3uYUks0NAU1lSFQKpYMw==
      Events:
