// ---------------------------------------------------------------------------
// Route registration — hand-maintained; add new handlers here.
//
// Adding a new route:
//   1. Create a handler function in `src/handlers/` with `#[route]`
//   2. Export the module in `src/handlers/mod.rs`
//   3. Import the generated handler struct below
//   4. Register it via `router.add_route(...)` in `add_routes()`
// ---------------------------------------------------------------------------

use iciaws_router::router::Router;

use crate::handlers::{
    users::GetUserHandler,
    versions::GetVersionHandler,
};

/// Registers all API route handlers with the provided [`Router`].
///
/// Routes are grouped by domain and registered in a consistent order.
/// Each handler struct (generated by the `#[route]` proc macro) exposes
/// a unique method+path key via `get_key()`.
pub fn add_routes(router: &mut Router) {
    // -- Version -----------------------------------------------------------
    router.add_route(GetVersionHandler::get_key(), Box::new(GetVersionHandler));

    // -- Users -------------------------------------------------------------
    router.add_route(GetUserHandler::get_key(), Box::new(GetUserHandler));
}
